apiVersion: v1
kind: ReplicationController
metadata:
  name: mypods
spec:
  replicas: 2
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myc1
          image: maha4iac/mahaonlinestore:1
          ports:
            - containerPort: 8080
