apiVersion: v1
kind: ReplicationController
metadata:
  name: mypods
spec:
  replicas: 2
  selector:
    app: myapp
    version: 2.6.3
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        version: 2.6.3
    spec:
      containers:
        - name: myc1
          image: maha4iac/mahaonlinestore:1
          ports:
            - containerPort: 8080
