apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myjavaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myc1
        image: harsh2589/myapp2
        ports:
        - containerPort: 8080
