apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myjavaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myjavaapp
        image: maha4iac/mahaonlinestore:2
        ports:
        - containerPort: 8080
