apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
    version: 2.6.4
spec:
  type: NodePort
  selector:
    app: myapp
    version: 2.6.4
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP