apiVersion: v1
kind: Service
metadata:
  name: muapp23
  labels: 
   app: myjavaapp
spec:
  type: NodePort
  selector:
    app: myjavaapp
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
